import os
os.system ('pkg install sl -y ')
os.system ('sl')
os.system ('clear')
os.system ('pkg install figlet')
os.system ('clear')
print ('\033[1;32m')
os.system ('figlet metasploit')
print ("")
print ("")
print ('\033[1;32m {1}\033[1;33m install metasploit in termux')
print ("")
print ('\033[1;32m {2}\033[1;33m Hack free fire ancont')
print ("")
print ("")
print ('\033[1;32mFor Example, Choose a Number \033[1;31m1,2,')
print ("")
v7x2 = input (" \033[1;33mfx9\033[1;31m==> ")
if v7x2 == '1' :
        os.system ('clear')
        os.system ('figlet metasploit')
        os.system ('pkg install wget curl openssh git -y')
        os.system ('pkg install ncurses-utils -y,')
        os.system ('wget  https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master/metasploit.sh')
        os.system ('chmod +x  metasploit.sh')
        os.system ('./metasploit.sh')
        os.system ('msfconsole')
